//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public string Title { get; set; }
        public int Price { get; set; }
        public string Category { get; set; }
        public string Company { get; set; }
        public string Pictures { get; set; }
        public int Purchase { get; set; }
    }
}
