//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaledProduct
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Sale { get; set; }
        public int Purchase { get; set; }
        public int Profit { get; set; }
        public System.DateTime Date { get; set; }
    }
}
